spring.application.name: customer-portal

server.port: 8082

security:
  ignored: /favicon.ico
  basic:
    enabled: false
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: customer-portal
      clientSecret: secret
      scope: openid,menu.read,order.me
    resource:
      jwt.keyUri: http://localhost:8080/uaa/token_key
