---
applications:
  - name: admin-portal
    path: target/microsec-admin-portal.jar
    memory: 1G
    env:
      TRUST_CERTS: api.sys.gcp.pcfapps.org
      SSO_IDENTITY_PROVIDERS: uaa
      GRANT_TYPE: authorization_code
      SSO_SCOPES: openid,menu.read,menu.write,order.admin,order.me
      SSO_AUTO_APPROVED_SCOPES: openid,menu.read,menu.write,order.admin,order.me
      SSO_SHOW_ON_HOME_PAGE: true
